name: CI

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  ci:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: 🛠 Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: 📦 Install
        run: npm ci

      - name: 🧑‍🏫 Check Format
        run: npm run format

      - name: 🕵️ Lint
        run: npm run lint

      - name: 👷‍♂️ Build
        run: npm run build

      - name: 📋 Collect Changes
        if: ${{ github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v') }}
        id: changes
        uses: simbo/changes-between-tags-action@v1

      - name: 📦 Create Release Package
        if: ${{ steps.changes.outcome == 'success' }}
        run: zip -r dist.zip dist

      - name: 🎁 Create GitHub Release
        if: ${{ steps.changes.outcome == 'success' }}
        uses: ncipollo/release-action@v1
        with:
          name: Release ${{ steps.changes.outputs.tag }}
          body: ${{ steps.changes.outputs.changes }}
          artifacts: dist.zip

      - name: 🚚 Deploy to GitHub Pages
        if: ${{ steps.changes.outcome == 'success' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          commit-message: Release ${{ github.ref_name }} from ${{ github.sha }}
